### ISSUE TITLE
MPI unit tests are failing

### ISSUE THREAD

**Issue by apteryks** [pyre/pyre#126]
Hello,

Running the test suite for 1.12.5, I see:

```
1227/1332 Test #1234: tests.mpi.pkg.mpirun.py ...............................................................................***Failed    0.55 sec
Traceback (most recent call last):
  File "/tmp/guix-build-pyre-1.12.5.drv-0/source/tests/mpi.pkg/./mpirun.py", line 56, in <module>
    test()
  File "/tmp/guix-build-pyre-1.12.5.drv-0/source/tests/mpi.pkg/./mpirun.py", line 46, in test
    status = app.run()
  File "/gnu/store/h5gzasawx28rj1dm7cyhvipgc1vgxbyz-pyre-1.12.5/packages/pyre/shells/Application.py", line 218, in run
    return self.shell.launch(self, *args, **kwds)
  File "/gnu/store/h5gzasawx28rj1dm7cyhvipgc1vgxbyz-pyre-1.12.5/packages/mpi/Launcher.py", line 67, in launch
    return self.spawn(application=application, *args, **kwds)
  File "/gnu/store/h5gzasawx28rj1dm7cyhvipgc1vgxbyz-pyre-1.12.5/packages/mpi/Launcher.py", line 104, in spawn
    argv = self.buildCommandLine()
  File "/gnu/store/h5gzasawx28rj1dm7cyhvipgc1vgxbyz-pyre-1.12.5/packages/mpi/Launcher.py", line 128, in buildCommandLine
    launcher = self.mpi.launcher
AttributeError: 'NoneType' object has no attribute 'launcher'

          Start 1259: tests.gsl.pkg.pdf_uniform_pos.py
1228/1332 Test #1235: tests.mpi.pkg.slurm.py ................................................................................***Failed    0.58 sec
Traceback (most recent call last):
  File "/tmp/guix-build-pyre-1.12.5.drv-0/source/tests/mpi.pkg/./slurm.py", line 56, in <module>
    test()
  File "/tmp/guix-build-pyre-1.12.5.drv-0/source/tests/mpi.pkg/./slurm.py", line 41, in test
    app.run()
  File "/gnu/store/h5gzasawx28rj1dm7cyhvipgc1vgxbyz-pyre-1.12.5/packages/pyre/shells/Application.py", line 218, in run
    return self.shell.launch(self, *args, **kwds)
  File "/gnu/store/h5gzasawx28rj1dm7cyhvipgc1vgxbyz-pyre-1.12.5/packages/mpi/Launcher.py", line 67, in launch
    return self.spawn(application=application, *args, **kwds)
  File "/gnu/store/h5gzasawx28rj1dm7cyhvipgc1vgxbyz-pyre-1.12.5/packages/mpi/Slurm.py", line 44, in spawn
    argv = self.buildCommandLine()
  File "/gnu/store/h5gzasawx28rj1dm7cyhvipgc1vgxbyz-pyre-1.12.5/packages/mpi/Launcher.py", line 128, in buildCommandLine
    launcher = self.mpi.launcher
AttributeError: 'NoneType' object has no attribute 'launcher'
```

I'm not sure why that happens; I'm using openmpi 4.1.6, and CMake is satisfied about it.

**Comment by aivazis** [comment]
This is almost certainly caused by improperly built `mpi` bindings. Try starting an interactive `python` session followed by
```
import mpi
print(mpi.libmpi)
```

If `libmpi` is `None`, the build of the `mpi` bindings is broken. Let me know what you see and we'll pick it up from there.

**Comment by Apteryks** [comment]
Oh! Indeed the `openmpi` package in Guix lacks Python bindings.  Perhaps Pyre's build system could check for their availaibility?  The configure script of openmpi doesn't build Python bindings by default:
```
  --enable-python-bindings
                          enable Python bindings (default: disabled)
```

**Comment by Apteryks** [comment]
ah, I think this flag gets passed to build the bundled openpmix package -- I'm using a system-provided openpmix so need to adjust this one instead.

**Comment by Apteryks** [comment]
I'm still at a loss ^^'.  I've enabled the Python bindings for the `openmpix` packaged used by `openmpi`, but that didn't change anything w.r.t. Python bindings for openmpi.  Will dig through its build system a bit more.

**Comment by Apteryks** [comment]
It seems openmpi's --enable-python-bindings really only does pass it to its bundled openpmix build -- so the result will be just a `pmix` module, as I've found.

Perhaps the `mpi` module is provided by a 3rd party library, e.g. https://pypi.org/project/mpi4py/ ?

**Comment by Apteryks** [comment]
Ah, apologies for the confusion, I hadn't realized that `pyre` itself provided openmpi python bindings:
```
$ find /gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/
/gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/
/gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/Cartesian.py
/gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/Communicator.py
/gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/Group.py
/gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/Launcher.py
/gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/Object.py
/gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/Port.py
/gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/Slurm.py
/gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/TrivialCommunicator.py
/gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/__init__.py
/gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/meta.py
/gnu/store/04mispg55bx5i7yjmb61x6j18zk64v9a-pyre-1.12.5/lib/python3.10/site-packages/mpi/mpi.cpython-310-x86_64-linux-gnu.so
```
Now to confirm whether they work or not.

**Comment by Apteryks** [comment]
> print(mpi.libmpi)

Seems to work:
```
In [1]: import mpi
import mpii

In [2]: print(mpi.libmpi)
print(mpi.libmpi))
<module 'mpi.mpi' from '/gnu/store/j8lbybq3hv22p229p719wqwc33492nkh-profile/lib/python3.10/site-packages/mpi/mpi.cpython-310-x86_64-linux-gnu.so'>
```

**Comment by Apteryks** [comment]
Ah, but in my earlier version of the package, PYTHONPATH was not extended with the site-packages of the just-built `pyre`.  Will try reinstating the tests following that.

**Comment by Apteryks** [comment]
`app.run()` runs successfully from an IPython debug session outside of the build environment.  Perhaps fails when there is no networking or X server or ? in the build environment.

**Comment by Apteryks** [comment]
Tried again in a `guix shell --container ipython pyre` container; indeed tkinter seems to trip on the lack of `DISPLAY`:
```
TclError                                  Traceback (most recent call last)
Cell In [22], line 1
----> 1 get_ipython().run_line_magic('paste', '')

File /gnu/store/8kkll8mqvlv96373bb8k07320i4rhvkk-python-ipython-8.5.0/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2309, in InteractiveShell.run_line_magic(self, magic_name, line, _stack_depth)
   2307     kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2308 with self.builtin_trap:
-> 2309     result = fn(*args, **kwargs)
   2310 return result

File /gnu/store/8kkll8mqvlv96373bb8k07320i4rhvkk-python-ipython-8.5.0/lib/python3.10/site-packages/IPython/terminal/magics.py:188, in TerminalMagics.paste(self, parameter_s)
    186     return
    187 try:
--> 188     block = self.shell.hooks.clipboard_get()
    189 except TryNext as clipboard_exc:
    190     message = getattr(clipboard_exc, 'args')

File /gnu/store/8kkll8mqvlv96373bb8k07320i4rhvkk-python-ipython-8.5.0/lib/python3.10/site-packages/IPython/core/hooks.py:116, in CommandChainDispatcher.__call__(self, *args, **kw)
    113 for prio,cmd in self.chain:
    114     #print "prio",prio,"cmd",cmd #dbg
    115     try:
--> 116         return cmd(*args, **kw)
    117     except TryNext as exc:
    118         last_exc = exc

File /gnu/store/8kkll8mqvlv96373bb8k07320i4rhvkk-python-ipython-8.5.0/lib/python3.10/site-packages/IPython/core/hooks.py:172, in clipboard_get(self)
    170 for func in chain:
    171     dispatcher.add(func)
--> 172 text = dispatcher()
    173 return text

File /gnu/store/8kkll8mqvlv96373bb8k07320i4rhvkk-python-ipython-8.5.0/lib/python3.10/site-packages/IPython/core/hooks.py:116, in CommandChainDispatcher.__call__(self, *args, **kw)
    113 for prio,cmd in self.chain:
    114     #print "prio",prio,"cmd",cmd #dbg
    115     try:
--> 116         return cmd(*args, **kw)
    117     except TryNext as exc:
    118         last_exc = exc

File /gnu/store/8kkll8mqvlv96373bb8k07320i4rhvkk-python-ipython-8.5.0/lib/python3.10/site-packages/IPython/lib/clipboard.py:62, in tkinter_clipboard_get()
     59 except ImportError as e:
     60     raise TryNext("Getting text from the clipboard on this platform requires tkinter.") from e
---> 62 root = Tk()
     63 root.withdraw()
     64 try:

File /gnu/store/jngpazr9y0s0304wqn0pjdm7ys0wrfbn-python-3.10.7/lib/python3.10/tkinter/__init__.py:2299, in Tk.__init__(self, screenName, baseName, className, useTk, sync, use)
   2297         baseName = baseName + ext
   2298 interactive = False
-> 2299 self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
   2300 if useTk:
   2301     self._loadtk()

TclError: no display name and no $DISPLAY environment variable
```

**Comment by Apteryks** [comment]
Hm, it runs even in a container.

**Comment by Apteryks** [comment]
I'm out of ideas.  Will close as something Guix-specific unrelated to this project for now.

**Comment by Apteryks** [comment]
Actually, I was able to reproduce this outside of the container, but using the same environment (including environment variables):
```
/tmp/guix-build-pyre-1.12.5.drv-3/build$ ctest -R mpi.pkg.mpirun.py
Test project /tmp/guix-build-pyre-1.12.5.drv-0/build
    Start 1234: tests.mpi.pkg.mpirun.py
1/1 Test #1234: tests.mpi.pkg.mpirun.py ..........***Failed    0.08 sec
Traceback (most recent call last):
  File "/tmp/guix-build-pyre-1.12.5.drv-0/source/tests/mpi.pkg/./mpirun.py", line 56, in <module>
    test()
  File "/tmp/guix-build-pyre-1.12.5.drv-0/source/tests/mpi.pkg/./mpirun.py", line 46, in test
    status = app.run()
  File "/gnu/store/h5gzasawx28rj1dm7cyhvipgc1vgxbyz-pyre-1.12.5/packages/pyre/shells/Application.py", line 218, in run
    return self.shell.launch(self, *args, **kwds)
  File "/gnu/store/h5gzasawx28rj1dm7cyhvipgc1vgxbyz-pyre-1.12.5/packages/mpi/Launcher.py", line 67, in launch
    return self.spawn(application=application, *args, **kwds)
  File "/gnu/store/h5gzasawx28rj1dm7cyhvipgc1vgxbyz-pyre-1.12.5/packages/mpi/Launcher.py", line 104, in spawn
    argv = self.buildCommandLine()
  File "/gnu/store/h5gzasawx28rj1dm7cyhvipgc1vgxbyz-pyre-1.12.5/packages/mpi/Launcher.py", line 128, in buildCommandLine
    launcher = self.mpi.launcher
AttributeError: 'NoneType' object has no attribute 'launcher'


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.10 sec

The following tests FAILED:
	1234 - tests.mpi.pkg.mpirun.py (Failed)
Errors while running CTest
```

**Comment by Apteryks** [comment]
Looks like I can easily reproduce this in a fresh build:
```
PYTHONPATH=../../build/install/packages python3.10 ./mpirun.py
Traceback (most recent call last):
  File "/home/maxim/src/pyre/tests/mpi.pkg/./mpirun.py", line 56, in <module>
    test()
  File "/home/maxim/src/pyre/tests/mpi.pkg/./mpirun.py", line 46, in test
    status = app.run()
  File "/home/maxim/src/pyre/build/install/packages/pyre/shells/Application.py", line 218, in run
    return self.shell.launch(self, *args, **kwds)
  File "/home/maxim/src/pyre/build/install/packages/mpi/Launcher.py", line 67, in launch
    return self.spawn(application=application, *args, **kwds)
  File "/home/maxim/src/pyre/build/install/packages/mpi/Launcher.py", line 104, in spawn
    argv = self.buildCommandLine()
  File "/home/maxim/src/pyre/build/install/packages/mpi/Launcher.py", line 128, in buildCommandLine
    launcher = self.mpi.launcher
AttributeError: 'NoneType' object has no attribute 'launcher'
```

**Comment by Apteryks** [comment]
I'm using Python 3.10.

**Comment by aivazis** [comment]
The mpi test suite was rebuilt in #190 with serial and multi-rank cases for each driver and unbound ranks for the launches, and it runs on every CI leg that has mpi. If the failure persists against v1.13.0, please reopen with the log and the mpi flavor and version.
