### ISSUE TITLE
Broken shebang in launcher

### ISSUE THREAD

**Issue by apteryks** [pyre/pyre#127]
Hi,

I've succeeded building pyre on GNU Guix using CMake (running almost all tests successfully), but trying a test run of the binary yields:

```
$ LANG=C /gnu/store/kxh7fkmqvan3wgqs276ngc627v2vkz15-pyre-1.12.5/bin/pyre
/usr/bin/env: 'python.pyre': No such file or directory

$ cat /gnu/store/kxh7fkmqvan3wgqs276ngc627v2vkz15-pyre-1.12.5/bin/pyre
#!/usr/bin/env python.pyre
# -*- Python -*-
# -*- coding: utf-8 -*-
#
# michael a.g. aïvázis
# orthologue
# (c) 1998-2024 all rights reserved
#

# get support
import pyre

# build a shell
shell = pyre.shells.interactive()(name='pyre.shell')
# make a context
context = {
    'pyre': pyre
}
# make a banner
banner = pyre.meta.header

# and launch it
shell.pyre_interactiveSession(banner=banner, context=context)

# configure the garbage collector
# import gc
# show me who has a handle to the pyre executive
# for entity in gc.get_referrers(pyre.executive):
    # print(type(entity))
    # print("   ", entity)

# end of file
```

It seems there should be a `python.pyre` on `PATH` for this to succeed, but the pyre package installed none. Ideas?

**Comment by Apteryks** [comment]
The smith.pyre binary also fails launching, apparently due to a missing template file:

```
PYTHONPATH=/gnu/store/l2r3kh90dhbpj4m3psigq32lgp76hip6-pyre-1.12.5/lib/python3.10/site-packages /gnu/store/l2r3kh90dhbpj4m3psigq32lgp76hip6-pyre-1.12.5/bin/smith.pyre 
smith: template: component 'smith.project', an instance of 'pyre.smith.projects.plexus'
smith: error while mounting '/gnu/store/l2r3kh90dhbpj4m3psigq32lgp76hip6-pyre-1.12.5/lib/python3.10/templates/plexus': mount point not found
Traceback (most recent call last):
  File "/gnu/store/l2r3kh90dhbpj4m3psigq32lgp76hip6-pyre-1.12.5/lib/python3.10/site-packages/pyre/shells/Script.py", line 51, in launch
    status = application.main(*args, **kwds)
  File "/gnu/store/l2r3kh90dhbpj4m3psigq32lgp76hip6-pyre-1.12.5/lib/python3.10/site-packages/pyre/smith/Smith.py", line 55, in main
    template = self.vfs.local(root=self.vault).discover()
  File "/gnu/store/l2r3kh90dhbpj4m3psigq32lgp76hip6-pyre-1.12.5/lib/python3.10/site-packages/pyre/framework/FileServer.py", line 145, in local
    return filesystem.local(root=str(root), **kwds)
  File "/gnu/store/l2r3kh90dhbpj4m3psigq32lgp76hip6-pyre-1.12.5/lib/python3.10/site-packages/pyre/filesystem/__init__.py", line 52, in local
    raise MountPointError(uri=root, error="mount point not found")
pyre.filesystem.exceptions.MountPointError: error while mounting '/gnu/store/l2r3kh90dhbpj4m3psigq32lgp76hip6-pyre-1.12.5/lib/python3.10/templates/plexus': mount point not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gnu/store/l2r3kh90dhbpj4m3psigq32lgp76hip6-pyre-1.12.5/bin/smith.pyre", line 16, in <module>
    status = app.run()
  File "/gnu/store/l2r3kh90dhbpj4m3psigq32lgp76hip6-pyre-1.12.5/lib/python3.10/site-packages/pyre/shells/Application.py", line 218, in run
    return self.shell.launch(self, *args, **kwds)
  File "/gnu/store/l2r3kh90dhbpj4m3psigq32lgp76hip6-pyre-1.12.5/lib/python3.10/site-packages/pyre/shells/Script.py", line 68, in launch
    application.error.log(str(error))
journal.ext.journal.ApplicationError: smith: application error
```

**Comment by aivazis** [comment]
The script in `bin/pyre` is meant to start an interactive `python` session with `pyre` preloaded using an embedding of `python` that includes additional support for debugging C/C++ extensions. The source code for the embedding is in `bin/python.cc`. When setting up the `cmake` build i skipped this step because getting `python` to link correctly with `make` seemed to be a bigger problem than it was worth at the time. I'll revisit.

**Comment by aivazis** [comment]
The `bin/smith.pyre` script is looking for its templates. The source code is in the `templates` directory in the repository. The `cmake` build skips the step of copying these static assets to the install directory, mostly because i don't know what is a good place to put them when the `pyre` package is installed in `lib/python3.xx/site-packages`. Does your distribution have any conventions for such things?

**Comment by Apteryks** [comment]
Perhaps under the `$prefix/share/pyre/templates` directory?  The Autoconf standards states that (c.f. `info '(standards) Directory Variables'`):

> Most packages install their data under '$(datadir)/PACKAGE-NAME/'.

where $datadir is 

>  The directory for installing idiosyncratic read-only architecture-independent data files for this program.

Typically on GNU/Linux distributions that's set to /share.

**Comment by Apteryks** [comment]
The important bit would be that smith.pyre is 'configured' by CMake with the correct path of the templates directory baked in.
