### ISSUE TITLE
Issues with terminal changes

### ISSUE THREAD

**Issue by rtburns-jpl** [pyre/pyre#26]
Our CI is having issues building since https://github.com/pyre/pyre/commit/34e720260a89464fe30c5bca8a590b48dc5f4fc7. Is pyre making assumptions about ansi escape sequences? Our docker builds probably just see plain text terminals.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/pyre/packages/pyre/__init__.py", line 209, in <module>
    executive.discover()
  File "/opt/pyre/packages/pyre/framework/Executive.py", line 536, in discover
    from ..shells import user, terminal
  File "/opt/pyre/packages/pyre/shells/__init__.py", line 157, in <module>
    from .Application import Application as application
  File "/opt/pyre/packages/pyre/shells/Application.py", line 21, in <module>
    class Application(pyre.component, metaclass=Director):
  File "/opt/pyre/packages/pyre/shells/Application.py", line 55, in Application
    pyre_renderer = Renderer()
  File "/opt/pyre/packages/pyre/components/Actor.py", line 138, in __call__
    instance = super().__call__(name=name, locator=locator, **kwds)
  File "/opt/pyre/packages/pyre/shells/Renderer.py", line 72, in __init__
    'firewall': terminal.ansi['light-red'],
  File "/opt/pyre/packages/pyre/components/Component.py", line 343, in __getattr__
    raise AttributeError(f"{self} has no attribute '{name}'") from None
AttributeError: an instance of 'pyre.terminals.plain' has no attribute 'ansi'
 Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/pyre/packages/pyre/__init__.py", line 209, in <module>
    executive.discover()
  File "/opt/pyre/packages/pyre/framework/Executive.py", line 536, in discover
    from ..shells import user, terminal
  File "/opt/pyre/packages/pyre/shells/__init__.py", line 157, in <module>
    from .Application import Application as application
  File "/opt/pyre/packages/pyre/shells/Application.py", line 21, in <module>
    class Application(pyre.component, metaclass=Director):
  File "/opt/pyre/packages/pyre/shells/Application.py", line 55, in Application
    pyre_renderer = Renderer()
  File "/opt/pyre/packages/pyre/components/Actor.py", line 138, in __call__
    instance = super().__call__(name=name, locator=locator, **kwds)
  File "/opt/pyre/packages/pyre/shells/Renderer.py", line 72, in __init__
    'firewall': terminal.ansi['light-red'],
  File "/opt/pyre/packages/pyre/components/Component.py", line 343, in __getattr__
    raise AttributeError(f"{self} has no attribute '{name}'") from None
AttributeError: an instance of 'pyre.terminals.plain' has no attribute 'ansi'
 CMake Error at /opt/conda/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Pyre (missing: PYRE_INCLUDE_DIR PYRE_LIB_DIR
  PYRE_PACKAGE_DIR) (found version "")
Call Stack (most recent call first):
  /opt/conda/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  .cmake/FindPyre.cmake:71 (find_package_handle_standard_args)
  .cmake/ConfigISCE.cmake:45 (FIND_PACKAGE)
  CMakeLists.txt:71 (CheckPyre)
```

**Comment by aivazis** [comment]
It looks like you are building with cmake. You probably just need to update your CMakeLists.txt to match the contents of the packages.pyre.shells directory; there are some new entries there

**Comment by rtburns-jpl** [comment]
Not sure what you mean - I'm able to compile locally with CMake and pyre imports without issues.

**Comment by aivazis** [comment]
There were a couple of new files added to the pyre/shells directory and I guessed that the failure was caused by not including these files when building in that directory. I haven't seen how the CMakeLists decides what to compile or not, and figured it just needed an update.

It turns out that the cause fo your failure was the {Plain} terminal didn't have null implementations of the new color palettes. I have fixed that and created a new release

**Comment by aivazis** [comment]
v1.9.4 should fix this. Could you please check?

**Comment by rtburns-jpl** [comment]
Latest commit looks good to me. I'll check it on our testing instances in the morning. Thanks!

**Comment by rtburns-jpl** [comment]
Never mind - a job just ran without any issues, so it looks like this is resolved. Thanks again!
