### ISSUE TITLE
Issue with read-only python package installation location

### ISSUE THREAD

**Issue by rtburns-jpl** [pyre/pyre#69]
Pyre wants to create an `etc` dir in a read-only location. I think this location is also incorrect - etc should be alongside lib, not alongside python's site-packages.
```
Traceback (most recent call last):
  File "/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/site-packages/pyre/filesystem/Folder.py", line 225, in _retrieve
    for name in uri.names: node = node.contents[name]
KeyError: 'etc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/site-packages/pyre/shells/Application.py", line 401, in pyre_mountPrivateFolder
    parent = prefix[folder]
  File "/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/site-packages/pyre/filesystem/Folder.py", line 184, in __getitem__
    return self._retrieve(uri=primitives.path(uri))
  File "/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/site-packages/pyre/filesystem/Folder.py", line 229, in _retrieve
    raise self.NotFoundError(
pyre.filesystem.exceptions.NotFoundError: while looking for 'etc': 'etc' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/wcfpgnzmf8r6byyqacqyyi566dpsm5j8-mm-4.1.0/bin/.mm-wrapped", line 997, in <module>
    app = mm(name='mm')
  File "/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/site-packages/pyre/shells/Director.py", line 67, in __call__
    app = super().__call__(name=name, globalAliases=globalAliases, locator=locator, **kwds)
  File "/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/site-packages/pyre/components/Actor.py", line 140, in __call__
    instance = super().__call__(name=name, locator=locator, implicit=implicit, **kwds)
  File "/nix/store/wcfpgnzmf8r6byyqacqyyi566dpsm5j8-mm-4.1.0/bin/.mm-wrapped", line 185, in __init__
    super().__init__(**kwds)
  File "/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/site-packages/pyre/shells/Application.py", line 186, in __init__
    self.pfs = self.pyre_mountPrivateFilespace()
  File "/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/site-packages/pyre/shells/Application.py", line 324, in pyre_mountPrivateFilespace
    self.pyre_mountApplicationFolders(pfs=pfs, prefix=home)
  File "/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/site-packages/pyre/shells/Application.py", line 380, in pyre_mountApplicationFolders
    self.pyre_mountPrivateFolder(pfs=pfs, prefix=prefix, folder=folder)
  File "/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/site-packages/pyre/shells/Application.py", line 405, in pyre_mountPrivateFolder
    parent = prefix.mkdir(name=folder)
  File "/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/site-packages/pyre/filesystem/Local.py", line 71, in mkdir
    uri.mkdir(**kwds)
  File "/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/site-packages/pyre/primitives/Path.py", line 524, in mkdir
    return os.mkdir(self, **kwds)
PermissionError: [Errno 13] Permission denied: '/nix/store/mb96np6ik1k50z1ki03bpdvfr3a59i7y-pyre-1.9.9/lib/python3.8/etc'
```

**Comment by aivazis** [comment]
wanna give it a whirl? there may be other places where assumptions about access to the filesystem are broken...

**Comment by rtburns-jpl** [comment]
Thanks, that seems to have fixed the pyre issue. Looks like mm has some more grievances about my directory structure, so I will open a separate issue over there.
